### ISSUE TITLE
Errors on running test.py

### ISSUE THREAD

**Issue by gstuntz** [LevPasha/Instagram-API-python#131]
python test.py
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    from InstagramAPI import InstagramAPI
  File "/Users/gstuntz/Desktop/Instagram-API/InstagramAPI.py", line 22, in <module>
    from moviepy.editor import VideoFileClip
  File "/Library/Python/2.7/site-packages/moviepy/editor.py", line 22, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "/Library/Python/2.7/site-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
    from moviepy.video.VideoClip import VideoClip
  File "/Library/Python/2.7/site-packages/moviepy/video/VideoClip.py", line 20, in <module>
    from .io.ffmpeg_writer import ffmpeg_write_image, ffmpeg_write_video
  File "/Library/Python/2.7/site-packages/moviepy/video/io/ffmpeg_writer.py", line 15, in <module>
    from moviepy.config import get_setting
  File "/Library/Python/2.7/site-packages/moviepy/config.py", line 38, in <module>
    FFMPEG_BINARY = get_exe()
  File "/Library/Python/2.7/site-packages/imageio/plugins/ffmpeg.py", line 86, in get_exe
    raise NeedDownloadError('Need ffmpeg exe. '
imageio.core.fetching.NeedDownloadError: Need ffmpeg exe. You can download it by calling:
  imageio.plugins.ffmpeg.download()

**Comment by lolaraigada** [comment]
I've tried to download it but it didn't work.
If you comment line 22 in InstagramAPI.py you could run test.py without any problems at least.

**Comment by gstuntz** [comment]
Will this affect the API procedures?

**Comment by markusila** [comment]
I get the same error, also commented the line 22 and also concerned about consequences of that commenting.

**Comment by dc500** [comment]
"brew install ffmpeg" fixed the above error for me. I then got "Request return 429 error!
Login success!"

**Comment by GonzaloZiadi** [comment]
Having same issues as @dc500
