### ISSUE TITLE
installation problem 2017 May

### ISSUE THREAD

**Issue by Bellman281** [LevPasha/Instagram-API-python#158]
While, insta bot works perfectly. dont know Why I can't intsall API? 
After installing pip install -r requirements.txt successfully. I got this error!
please help me.

```
Traceback (most recent call last):
  File "D:\Instagram-API-python-master\Instagram-API-python-master\test.py", line 6, in <module>
    from InstagramAPI import InstagramAPI
  File "D:\Instagram-API-python-master\Instagram-API-python-master\InstagramAPI\__init__.py", line 25, in <module>
    from moviepy.editor import VideoFileClip
  File "D:\Python27\lib\site-packages\moviepy\editor.py", line 22, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "D:\Python27\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 3, in <module>
    from moviepy.video.VideoClip import VideoClip
  File "D:\Python27\lib\site-packages\moviepy\video\VideoClip.py", line 20, in <module>
    from .io.ffmpeg_writer import ffmpeg_write_image, ffmpeg_write_video
  File "D:\Python27\lib\site-packages\moviepy\video\io\ffmpeg_writer.py", line 15, in <module>
    from moviepy.config import get_setting
  File "D:\Python27\lib\site-packages\moviepy\config.py", line 38, in <module>
    FFMPEG_BINARY = get_exe()
  File "D:\Python27\lib\site-packages\imageio\plugins\ffmpeg.py", line 86, in get_exe
    raise NeedDownloadError('Need ffmpeg exe. '
NeedDownloadError: Need ffmpeg exe. You can download it by calling:
  imageio.plugins.ffmpeg.download()
```

**Comment by alekseynp** [comment]
In a python shell I typed
```
import imageio
imageio.plugins.ffmpeg.download()
```
And that error went away.
