### ISSUE TITLE
Trying to extract my own following list username, but stuck on errors when starting test.py

### ISSUE THREAD

**Issue by zhen737** [LevPasha/Instagram-API-python#176]
Hi,
As title, I've been trying my best to find the errors and issues my ownself, but have no luck, so may I know did I missed any critical step? 

```
` Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\site-packages\imageio\plugins\ffmpeg.py", line 99, in get_exe
    auto=False)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\site-packages\imageio\core\fetching.py", line 102, in get_remote_file
    raise NeedDownloadError()
imageio.core.fetching.NeedDownloadError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PC\Desktop\Instagram-API-python-master\test.py", line 6, in <module>
    from InstagramAPI import InstagramAPI
  File "C:\Users\PC\Desktop\Instagram-API-python-master\InstagramAPI\__init__.py", line 30, in <module>
    from moviepy.editor import VideoFileClip
  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\site-packages\moviepy\editor.py", line 22, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 3, in <module>
    from moviepy.video.VideoClip import VideoClip
  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\site-packages\moviepy\video\VideoClip.py", line 20, in <module>
    from .io.ffmpeg_writer import ffmpeg_write_image, ffmpeg_write_video
  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\site-packages\moviepy\video\io\ffmpeg_writer.py", line 15, in <module>
    from moviepy.config import get_setting
  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\site-packages\moviepy\config.py", line 38, in <module>
    FFMPEG_BINARY = get_exe()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\site-packages\imageio\plugins\ffmpeg.py", line 103, in get_exe
    raise NeedDownloadError('Need ffmpeg exe. '
imageio.core.fetching.NeedDownloadError: Need ffmpeg exe. You can obtain it with either:
  - install using conda: conda install ffmpeg -c conda-forge
  - download by calling: imageio.plugins.ffmpeg.download() `
```

**Comment by the-rccg** [comment]
This is not an issue of the API, but a missing dependency on your end. The last three lines of the error even explicitly mention how to resolve it. Open up a console and execute the given conda command and your problem is solved. 

"imageio.core.fetching.NeedDownloadError: Need ffmpeg exe. You can obtain it with either:
  - install using conda: conda install ffmpeg -c conda-forge
  - download by calling: imageio.plugins.ffmpeg.download() "

**Comment by ekremgurdal** [comment]
are you using windows or linux?

**Comment by zhen737** [comment]
@ekremgurdal  
> are you using windows or linux?

I am using Windows 64bit, Pythons 3.6

**Comment by ekremgurdal** [comment]
@zhen737 try this: 

Open CMD, then 

cd C:\Users\PC\AppData\Local\Programs\Python\Python36\Scripts
pip3 install moviepy
pip3 install imageio

After that

change ffmpeg.py 82th line from auto=False to auto=True

Then import imageio in your code and write down imageio.plugins.ffmpeg.download()
It will automatically download ffmpeg to the correct path once.
