### ISSUE TITLE
ImportError: No module named 'requests_toolbelt'

### ISSUE THREAD

**Issue by hanachan1026** [LevPasha/Instagram-API-python#325]
Hi I got this error even though I have this library.
/usr/local/lib/python3.6/requests_toolbelt

And I installed the dependencies also.

% python3 test.py

Traceback (most recent call last):
  File "test.py", line 6, in <module>
    from InstagramAPI import InstagramAPI
  File "/Users/name/tools/Instagram-API-python/InstagramAPI/__init__.py", line 1, in <module>
    from .InstagramAPI import *
  File "/Users/name/tools/Instagram-API-python/InstagramAPI/InstagramAPI.py", line 18, in <module>
    from requests_toolbelt import MultipartEncoder
ImportError: No module named 'requests_toolbelt'

Any help??

**Comment by Seriusam** [comment]
Were you able to find the problem ?

**Comment by hanachan1026** [comment]
Yes, I was using diffrent versions of python3 and pip3, it caused the
problem.

2018年2月28日(水) 8:20 Seriusam <notifications@github.com>:
