### ISSUE TITLE
Proxy Issues, Help would be appreciated!

### ISSUE THREAD

**Issue by Haydardi** [LevPasha/Instagram-API-python#337]
Hi guys!

I'm getting this error every time I try to login to my instagram through the API. This started happening since yesterday. I don't know if I messed something up with my linux/ubunto server or what not, any advice on how to fix this would be awesome!

`accounts.py Error: 
Traceback (most recent call last):
  File "/var/www/FlaskApp/FlaskApp/routes/accounts.py", line 381, in connect_to_database
    stat = login(username, password, proxy, c, conn)
  File "/var/www/FlaskApp/FlaskApp/routes/accounts.py", line 595, in login
    st, whatProx = API.login()
  File "/var/www/FlaskApp/FlaskApp/WEBBOT/IGBotScripts/Instagram_API/__init__.py", line 189, in login
    if (self.SendRequest('si/fetch_headers/?challenge_type=signup&guid=' + self.generateUUID(False), None, True)):
  File "/var/www/FlaskApp/FlaskApp/WEBBOT/IGBotScripts/Instagram_API/__init__.py", line 974, in SendRequest
    response = self.s.get(self.API_URL + endpoint, verify=verify)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 502, in send
    raise ProxyError(e, request=request)
ProxyError: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/si/fetch_headers/?challenge_type=signup&guid=ce694eb4fd59498d8cf4644a134766e6 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f29b105b850>: Failed to establish a new connection: [Errno -2] Name or service not known',)))
 

`

ps. this only happens when I use proxy and does not happen when I remove the proxy.

**Comment by LevPasha** [comment]
Cannot connect to proxy...
