### ISSUE TITLE
next_max_id only goes up to 300 times

### ISSUE THREAD

**Issue by fernaoguerra** [LevPasha/Instagram-API-python#420]
I got an error when running the **user_followers.py** sample: https://github.com/LevPasha/Instagram-API-python/blob/master/examples/user_followers.py

It runs up to 300 pages then I got the erro:

Traceback (most recent call last):
  File "count.py", line 54, in <module>
    followers = api.getTotalFollowers(user_id)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/InstagramAPI/InstagramAPI.py", line 865, in getTotalFollowers
    for item in temp["users"]:
KeyError: 'users'

I can't reach more than 59689 followers.

Anyone?
Thanks!

**Comment by fernaoguerra** [comment]
@Ilario17 I did not solve it? Still looking? Do you have any ideas?

**Comment by Ilario17** [comment]
@fernaoguerra I'm testing... for now I've tested with an account with 17k followers. 

It is very slow to read them all, and it seems to me really strange that there is no way to directly ask the count of follower/ing without having to wait so many minutes.

how long do you take to get the complete list of 60k followers?

**Comment by sahiltspaceo** [comment]
@fernaoguerra any updates? I cannot even fetch 600 followers. getting only 185. can you share your snippet?

**Comment by fernaoguerra** [comment]
Hi @sahiltspaceo, no I did not solve it with this solution.
Try to use this  instead: https://github.com/timgrossmann/InstaPy
Last time I used this one.
