### ISSUE TITLE
sending a direct message 

### ISSUE THREAD

**Issue by matthewtranmer** [LevPasha/Instagram-API-python#475]
from InstagramAPI import InstagramAPI

InstagramAPI = InstagramAPI("name", "pass")
InstagramAPI.login()                        # login
mediaId = '1469246128228859784_1520786701'    # a media_id
recipients = ["matthew_tranmer"]                             # array of user_ids. They can be strings or ints
InstagramAPI.direct_share(mediaId, recipients, text='hello')

when i run this code i get:

Traceback (most recent call last):
  File "C:\Users\Me\Desktop\Instagram-API-python-master\examples\direct_share.py", line 12, in <module>
    InstagramAPI.direct_share(mediaId, recipients, text='aquest es es darrer')
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\site-packages\InstagramAPI\InstagramAPI.py", line 389, in direct_share
    if not isinstance(position, list):
NameError: name 'position' is not defined

please can somebody help!

**Comment by Cassianokunsch** [comment]
Because in recipients you need to pass a userId, and not a username, you can get using this

api = InstagramAPI(username, password)
api.login()
api.searchUsername('your username') #example 'cassianokunsch'
response = api.LastJson
user_id = response['user']['pk']

after this you can put user_id on the recipients

**Comment by tinlm** [comment]
What if you get this?

direct_message() missing 1 required positional argument: 'recipients'

**Comment by Cassianokunsch** [comment]
The function direct_message() needs recipients. Recipients is a list of pk. You get it using 

api.searchUsername('your username') #example 'cassianokunsch'
response = api.LastJson
pk = response['user']['pk']

**Comment by atwine** [comment]
> Because in recipients you need to pass a userId, and not a username, you can get using this
> 
> api = InstagramAPI(username, password)
> api.login()
> api.searchUsername('your username') #example 'cassianokunsch'
> response = api.LastJson
> user_id = response['user']['pk']
> 
> after this you can put user_id on the recipients

Hello,  can I use this function to send direct message to a bunch of my followers? I am trying to piece this together.

How about if I want it to message a new follower direct?

**Comment by Cassianokunsch** [comment]
> > Because in recipients you need to pass a userId, and not a username, you can get using this
> > api = InstagramAPI(username, password)
> > api.login()
> > api.searchUsername('your username') #example 'cassianokunsch'
> > response = api.LastJson
> > user_id = response['user']['pk']
> > after this you can put user_id on the recipients
> 
> Hello, can I use this function to send direct message to a bunch of my followers? I am trying to piece this together.
> 
> How about if I want it to message a new follower direct?

Hello, so first sorry for my english, i'm Brazilian kk. If you search on internet you will find this information, but i think you need a create a service or one while inside a function where you need all the time get your followers and check if you get a new and send a message for him.

**Comment by atwine** [comment]
Okay that sounds doable. Thanks

**Comment by ethanbailey19** [comment]
im having problems with the ( TypeError: direct_share() missing 1 required positional argument: 'recipients' ) how did you all fix it ??

this is my hole code 

InstagramAPI import InstagramAPI

api= InstagramAPI("--------------", "----------")
api.login() 

api.searchUsername('-------------')
response = api.LastJson
user_id = response['user']['pk']
mediaId = '1469246128228859784_1520786701' #i dont know what this is but was on sourse code
recipients = [user_id]
text=("hey")
InstagramAPI.direct_share(recipients, text)
