### ISSUE TITLE
Only able to send 1 DM

### ISSUE THREAD

**Issue by ssmmoo1** [LevPasha/Instagram-API-python#568]
I have a basic chatbot replying to direct messages but the bot will successfully send 1 message per user but then the second message will be sent and the direct_message() function returns true but the when I check the inbox the second message was never sent. 

The only way I can send another DM is if I logout, recreate the api and log in again. 

I've tested this in a script and then manually with the python console to confirm its not a programming error.

**Comment by ndorl** [comment]
Could I ask you please what code are you using to send direct messages?

**Comment by itkos** [comment]
@ndorl Please! Look in my issue https://github.com/LevPasha/Instagram-API-python/issues/547

**Comment by jvmachadorj** [comment]
It is also happened to me, I'm able to send only one message at a time.

I'm testing in the terminal

```
 from InstagramAPI import InstagramAPI
x = InstagramAPI('user', 'password')
x.login()
x.direct_message('hello, this is a test 1/2', user_id) 
```

When I try to send again

`x.direct_message('hello, this is a test 2/2', user_id) 
`
It doesnt work

**Comment by kenveys** [comment]
Hi,

The problem is that the uuid is not renewed for every direct message.
add this line in def direct_message before using the uuid:
self.uuid = self.generateUUID(True)

cheers,

**Comment by Asteur** [comment]
Also, you may relogin and send message

**Comment by ethanbailey19** [comment]
im having problems with the ( TypeError: direct_share() missing 1 required positional argument: 'recipients' ) how did you all fix it ??

this is my hole code

InstagramAPI import InstagramAPI

api= InstagramAPI("--------------", "----------")
api.login()

api.searchUsername('-------------')
response = api.LastJson
user_id = response['user']['pk']
mediaId = '1469246128228859784_1520786701' #i dont know what this is but was on sourse code
recipients = [user_id]
text=("hey")
InstagramAPI.direct_share(recipients, text)

**Comment by Asteur** [comment]
> im having problems with the ( TypeError: direct_share() missing 1 required positional argument: 'recipients' ) how did you all fix it ??
> 
> this is my hole code
> 
> InstagramAPI import InstagramAPI
> 
> api= InstagramAPI("--------------", "----------")
> api.login()
> 
> api.searchUsername('-------------')
> response = api.LastJson
> user_id = response['user']['pk']
> mediaId = '1469246128228859784_1520786701' #i dont know what this is but was on sourse code
> recipients = [user_id]
> text=("hey")
> InstagramAPI.direct_share(recipients, text)

api.direct_message("hey", recipients)
instead of InstagramAPI.direct_share(recipients, text)

**Comment by Asteur** [comment]
> im having problems with the ( TypeError: direct_share() missing 1 required positional argument: 'recipients' ) how did you all fix it ??
> 
> this is my hole code
> 
> InstagramAPI import InstagramAPI
> 
> api= InstagramAPI("--------------", "----------")
> api.login()
> 
> api.searchUsername('-------------')
> response = api.LastJson
> user_id = response['user']['pk']
> mediaId = '1469246128228859784_1520786701' #i dont know what this is but was on sourse code
> recipients = [user_id]
> text=("hey")
> InstagramAPI.direct_share(recipients, text)

Try api.direct_share(mediaId, recipients, "hey")

**Comment by ethanbailey19** [comment]
i know get this

Traceback (most recent call last):
  File "C:\Users\Ethan\Desktop\tester\api\ig.py", line 13, in <module>
    api.direct_share(mediaId, user_id, text)
  File
"C:\Users\Ethan\AppData\Local\Programs\Python\Python36\lib\site-packages\InstagramAPI\InstagramAPI.py",
line 389, in direct_share
    if not isinstance(position, list):
NameError: name 'position' is not defined

**Comment by Asteur** [comment]
> i know get this Traceback (most recent call last): File "C:\Users\Ethan\Desktop\tester\api\ig.py", line 13, in <module> api.direct_share(mediaId, user_id, text) File "C:\Users\Ethan\AppData\Local\Programs\Python\Python36\lib\site-packages\InstagramAPI\InstagramAPI.py", line 389, in direct_share if not isinstance(position, list): NameError: name 'position' is not defined
> […](#)

What do you want to achieve with direct_share? this issue is about direct_message()

**Comment by ethanbailey19** [comment]
Direct message did not work so I found someone had used direct share

**Comment by ethanbailey19** [comment]
Traceback (most recent call last):
  File "C:\Users\Ethan\Desktop\tester\api\ig.py", line 18, in <module>
    api.direct_message(mediaId, user_id, "hey")
AttributeError: 'InstagramAPI' object has no attribute 'direct_message'

**Comment by Asteur** [comment]
> Direct message did not work so I found someone had used direct share
> […](#)

Install from this repository
pip install git+https://github.com/LevPasha/Instagram-API-python.git
and then api.direct_message(message, user)

**Comment by ethanbailey19** [comment]
that is where i got it from does the pip install not work

**Comment by ethanbailey19** [comment]
hey just to say thank you for all the help i had downloaded it all and now
getting this as my output in python idle shell

Fail to import moviepy. Need only for Video upload.
Request return 429 error!
{'message': 'Please wait a few minutes before you try again.', 'status':
'fail'}
Request return 405 error!
{'message': '', 'status': 'fail'}
Request return 404 error!
Login success!

Request return 500 error!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
