### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by eduhh94** [LevPasha/Instagram-API-python#602]
When I follow the guide and try to execute test.py (which is in examples) I get this message:

`python3 test.py
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    from InstagramAPI import InstagramAPI
ModuleNotFoundError: No module named 'InstagramAPI'`

**Comment by venomsnake1994** [comment]
hello this issues is for the name .. the problem is the folder  and file and class name are same so change the folder or file name and you good to go .
I change file name to API 
from API import InstagramAPI

**Comment by eduhh94** [comment]
Hi, I did the same but still get same error
```

$ python test.py 
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    from API import InstagramAPI
ImportError: No module named API
```

**Comment by venomsnake1994** [comment]
if you didn't install via pip  you must be  change your working directory in cmd or terminal in same folder

**Comment by eduhh94** [comment]
Still not working did this:
```
$ cd Instagram-API-python
$ python examples/test.py 
Traceback (most recent call last):
  File "examples/test.py", line 6, in <module>
    from API import InstagramAPI
ImportError: No module named API
```

**Comment by venomsnake1994** [comment]
I explain by default name 
cd Instagram-api-python-maste  -> antoher cd to   folder name ("InstagramAPI") 
and then there is module name "InstagramAPI" so you change it API 
go to python 
now you can do from API import InstagramAPI

**Comment by eduhh94** [comment]
I now managed to install InstagramAPI over pip and it's working. But I'm still curious how to get it work without. Do you have maybe a link for me with some information regarding this topic?

**Comment by venomsnake1994** [comment]
send you skype or email  I will send or explain

**Comment by eduhh94** [comment]
Sure my e-mail is eduardh94@gmail.com <mailto:eduardh94@gmail.com>

**Comment by venomsnake1994** [comment]
https://docs.python.org/3/reference/import.html

**Comment by eduhh94** [comment]
Alright thanks. I will work through later. Appreciate your help.
