### ISSUE TITLE
pip install InstagramAPI error

### ISSUE THREAD

**Issue by eduhh94** [LevPasha/Instagram-API-python#605]
When I try to install InstagramAPI over pip I get an error:

```
$ pip install InstagramApi

You are using pip version 6.1.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting InstagramApi
  Using cached https://files.pythonhosted.org/packages/15/6d/f7eba7679fb40acb33ac75960c1aff269c2a75b32aff106266c85e3c0b93/InstagramAPI-1.0.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): requests==2.11.1 in /Library/Python/2.7/site-packages (from InstagramApi)
Requirement already satisfied (use --upgrade to upgrade): requests-toolbelt==0.7.0 in /Library/Python/2.7/site-packages (from InstagramApi)
Collecting moviepy==0.2.3.2 (from InstagramApi)
  Using cached https://files.pythonhosted.org/packages/e4/1f/fb4b8d9397f7952fcb594cb5df3061f00debae7ea92b3be9881c18b905ab/moviepy-0.2.3.2-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): decorator==4.0.11 in /Library/Python/2.7/site-packages (from moviepy==0.2.3.2->InstagramApi)
Requirement already satisfied (use --upgrade to upgrade): tqdm==4.11.2 in /Library/Python/2.7/site-packages (from moviepy==0.2.3.2->InstagramApi)
Collecting imageio==2.1.2 (from moviepy==0.2.3.2->InstagramApi)
  Using cached https://files.pythonhosted.org/packages/68/31/55cad23b6bd32afee6e4c7eec2f15266665879f8eaf812e3b843205d41ad/imageio-2.1.2.zip
Requirement already satisfied (use --upgrade to upgrade): numpy in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from moviepy==0.2.3.2->InstagramApi)
Collecting pillow (from imageio==2.1.2->moviepy==0.2.3.2->InstagramApi)
  Using cached https://files.pythonhosted.org/packages/3c/7e/443be24431324bd34d22dd9d11cc845d995bcd3b500676bcf23142756975/Pillow-5.4.1.tar.gz
Installing collected packages: pillow, imageio, moviepy, InstagramApi
  Running setup.py install for pillow
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/0g/d3g5sljs79df7bbm9ty3k9tw0000gn/T/pip-build-fozD7y/pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/0g/d3g5sljs79df7bbm9ty3k9tw0000gn/T/pip-41b91B-record/install-record.txt --single-version-externally-managed --compile:
    /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14-intel-2.7
    creating build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/MpoImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/ImageMode.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/PngImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/XbmImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/PcxImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/SunImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/ImageFile.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/SpiderImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/TarIO.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/FitsStubImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/MpegImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/BdfFontFile.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/GribStubImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/ImageStat.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/PixarImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/GimpPaletteFile.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/ImageColor.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/ContainerIO.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/MspImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/MicImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/_version.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/ImtImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/GifImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/PalmImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/ImageQt.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/ImageMath.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/PaletteFile.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/FontFile.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/PdfParser.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/ExifTags.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/ImageCms.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/FpxImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/ImageChops.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/BufrStubImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/PSDraw.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/PcdImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/ImageFilter.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/ImageDraw2.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/ImagePath.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/DcxImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/__init__.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/JpegPresets.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/features.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/ImageDraw.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/GimpGradientFile.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/ImageWin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/IcoImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/_tkinter_finder.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/EpsImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/TgaImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/ImageMorph.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/WalImageFile.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/PcfFontFile.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/BlpImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/ImageTk.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/GbrImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/ImageOps.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/PdfImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/ImageShow.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/ImageEnhance.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/WmfImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/ImageGrab.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/WebPImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/FliImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/TiffTags.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/CurImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/_util.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/GdImageFile.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/TiffImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/IptcImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/ImagePalette.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/BmpImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/ImageTransform.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/IcnsImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/McIdasImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/XpmImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/OleFileIO.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/DdsImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/ImageSequence.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/PyAccess.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/_binary.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/Image.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/XVThumbImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/SgiImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/ImImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/PsdImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/JpegImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/ImageFont.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/PpmImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    copying src/PIL/FtexImagePlugin.py -> build/lib.macosx-10.14-intel-2.7/PIL
    running egg_info
    writing src/Pillow.egg-info/PKG-INFO
    writing top-level names to src/Pillow.egg-info/top_level.txt
    writing dependency_links to src/Pillow.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching '.travis'
    warning: no previously-included files found matching '.travis/*'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
    running build_ext
    
    
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0g/d3g5sljs79df7bbm9ty3k9tw0000gn/T/pip-build-fozD7y/pillow/setup.py", line 812, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException: 
    
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    
    
    ----------------------------------------
    Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/0g/d3g5sljs79df7bbm9ty3k9tw0000gn/T/pip-build-fozD7y/pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/0g/d3g5sljs79df7bbm9ty3k9tw0000gn/T/pip-41b91B-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/0g/d3g5sljs79df7bbm9ty3k9tw0000gn/T/pip-build-fozD7y/pillow
```

**Comment by eduhh94** [comment]
Solution: upgrade pip
`sudo pip install --upgrade pip`

**Comment by Glarity** [comment]
Close issue please :)
