### ISSUE TITLE
I can't upload video

### ISSUE THREAD

**Issue by Pingu-Io** [LevPasha/Instagram-API-python#656]
When i try to upload a video i get this error:

Traceback (most recent call last):
  File "C:\Users\saram\Desktop\InstaBot\index.py", line 68, in <module>
    InstagramAPI.uploadPhoto(img_path_jpg, caption=descrizione_jpg)
  File "C:\Users\saram\AppData\Local\Programs\Python\Python37-32\lib\site-packages\InstagramAPI\InstagramAPI.py", line 162, in uploadPhoto
    if self.configure(upload_id, photo, caption):
  File "C:\Users\saram\AppData\Local\Programs\Python\Python37-32\lib\site-packages\InstagramAPI\InstagramAPI.py", line 474, in configure
    (w, h) = getImageSize(photo)
  File "C:\Users\saram\AppData\Local\Programs\Python\Python37-32\lib\site-packages\InstagramAPI\ImageUtils.py", line 32, in getImageSize
    raise RuntimeError("Unsupported format")
RuntimeError: Unsupported format

**Comment by apepenkov** [comment]
You are trying to upload photo
