### ISSUE TITLE
challenge_required issues

### ISSUE THREAD

**Issue by LivC182** [LevPasha/Instagram-API-python#743]
Anybody who can figure out how the class is bypassing challenge_required message ? 

For me the package works perfect no errors. I tried to create my custom package and got challenge_required, I copied all the headers here and still get challenge_required.

**Comment by DeF3c** [comment]
Try this:
api = InstagramAPI("yourusername", "yourpassword", False)
api.login()
time.sleep(10)
api.login()
if(api.isLoggedIn == True):
    print("Still logged in")
//Code here

I dont know why, but this worked for me.
Just wait for the Message still logged in, dont panic if there any error messages. Just wait until the message is coming

**Comment by Exordio** [comment]
```
`Request return 400 error!
{'message': 'challenge_required', 'challenge': {'url':`
```
does not help :(

**Comment by Exordio** [comment]
> 
> 
> Try this:
> api = InstagramAPI("yourusername", "yourpassword", False)
> api.login()
> time.sleep(10)
> api.login()
> if(api.isLoggedIn == True):
> print("Still logged in")
> //Code here
> 
> I dont know why, but this worked for me.
> Just wait for the Message still logged in, dont panic if there any error messages. Just wait until the message is coming
```
`
Request return 400 error!
{'message': 'challenge_required', 'challenge': {'url': 'https://i.instagram.com/challenge/7280146208/9FzWTax0AD/', 'api_path': '/challenge/7280146208/9FzWTax0AD/', 'hide_webview_header': True, 'lock': True, 'logout': False, 'native_flow': True}, 'status': 'fail', 'error_type': 'checkpoint_challenge_required'}
Request return 400 error!
{'message': 'challenge_required', 'challenge': {'url': 'https://i.instagram.com/challenge/7280146208/9FzWTax0AD/', 'api_path': '/challenge/7280146208/9FzWTax0AD/', 'hide_webview_header': True, 'lock': True, 'logout': False, 'native_flow': True}, 'status': 'fail', 'error_type': 'checkpoint_challenge_required'}
Traceback (most recent call last):
  File "Q:\Python_Projects\instexplore\instagram_Smart_Scrapy.py", line 42, in <module>
    instAPI.getProfileData()
  File "q:\python_projects\instexplore\venv\src\instagramapi\InstagramAPI\InstagramAPI.py", line 639, in getProfileData
    '_uid': self.username_id,
AttributeError: 'InstagramAPI' object has no attribute 'username_id'

Process finished with exit code 1
`

```

**Comment by ok52989** [comment]
DEFC when you say try this can you explain where to copy and paste that text. I am new to python.
